### ISSUE TITLE
Udary Mod release link needs updating.

### ISSUE THREAD

**Issue by mabrowning** [mount2010/tfcplusdiscordbot#1]
https://github.com/mount2010/tfcplusdiscordbot/blob/8be10cc0d9f6aba9789bed17a3cc3e2e2aaed35a/data/addons.json#L66

Should probably point to https://github.com/Bletch1971/TFCPlusUdaryMod/tree/master/tfc_0.80.18 instead.

**Comment by mount2010** [comment]
Hmmm. I might link to the main page instead, since linking to that specific folder is bound to change if @Bletch1971 ever updated it. It'd be easier if Bletch had used Releases.
